export enum EError {
    NOT_FOUND = 'NOT_FOUND',
    BAD_REQUEST = 'BAD_REQUEST',
    UNAUTHORIZED = 'UNAUTHORIZED',
    FORBIDDEN = 'FORBIDDEN',
    UNPROCESSABLE_ENTITY = 'UNPROCESSABLE_ENTITY',
    CONFLICT = 'CONFLICT',
    JSON_WEB_TOKEN='JsonWebTokenError',
    PAYMENT_REQUIRED = 'PAYMENT_REQUIRED',
}